dependencies = [ "once_cell = \"=1.18.0\"", "static_assertions = \"=1.1.0\"", "varisat = \"=0.2.2\"", "memoise = \"=0.3.2\"", "argio = \"=0.2.0\"", "ac-library-rs = \"=0.1.1\"",]

[package]
name = "tools"
version = "1.0.0"
authors = []
edition = "2018"

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false
