[[bin]]
name = "rco-contest-2019-qual-a"
path = "src/bin/a.rs"

[[bin]]
name = "rco-contest-2019-qual-b"
path = "src/bin/b.rs"

[package]
name = "rco-contest-2019-qual"
version = "0.1.0"
edition = "2018"

[dependencies]

[dev-dependencies]

[package.metadata.cargo-compete.bin.rco-contest-2019-qual-a]
alias = "a"
problem = "https://atcoder.jp/contests/rco-contest-2019-qual/tasks/rco_contest_2019_qual_a"

[package.metadata.cargo-compete.bin.rco-contest-2019-qual-b]
alias = "b"
problem = "https://atcoder.jp/contests/rco-contest-2019-qual/tasks/rco_contest_2019_qual_b"
