#!/usr/bin/env python3
# from typing import *



# def solve(N: int, a: List[int], b: List[int], M: int, x: List[int], y: List[int]) -> int:
def solve(N, a, b, M, x, y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = [None for _ in range(N)]
    b = [None for _ in range(N)]
    for i in range(N):
        a[i], b[i] = map(int, input().split())
    M = int(input())
    x = [None for _ in range(M)]
    y = [None for _ in range(M)]
    for i in range(M):
        x[i], y[i] = map(int, input().split())
    a1 = solve(N, a, b, M, x, y)
    print(a1)

if __name__ == '__main__':
    main()
