#!/usr/bin/env python3
# from typing import *



# def solve(W: int, H: int, N: int, x: List[int], y: List[int], a: List[int]) -> int:
def solve(W, H, N, x, y, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    W, H, N = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    a = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i], a[i] = map(int, input().split())
    a1 = solve(W, H, N, x, y, a)
    print(a1)

if __name__ == '__main__':
    main()
