[package]
name = "competitive-programming"
version = "0.1.0"
authors = ["otsuneko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["field/contests/atcoder/abc270", "field/contests/atcoder/practice", "field/contests/atcoder/abc269", "field/contests/atcoder/abc282", "field/contests/atcoder/abc139", "field/contests/atcoder/abc156", "field/contests/atcoder/abc046", "field/contests/atcoder/agc004", "field/contests/atcoder/abc121", "field/contests/atcoder/abc093", "field/contests/atcoder/abc079", "field/contests/atcoder/abc120", "field/contests/atcoder/abc055", "field/contests/atcoder/abc083", "field/contests/atcoder/abc091", "field/contests/atcoder/abc088", "field/contests/atcoder/abc103", "field/contests/atcoder/abc106", "field/contests/atcoder/abc283", "field/contests/atcoder/abc100", "field/contests/atcoder/abc087", "field/contests/atcoder/agc019", "field/contests/atcoder/abc144", "field/contests/atcoder/agc041", "field/contests/atcoder/abc151", "field/contests/atcoder/abc115", "field/contests/atcoder/agc021", "field/contests/atcoder/abc281", "field/contests/atcoder/abc272", "field/contests/atcoder/abc268", "field/contests/atcoder/abc267", "field/contests/atcoder/abc236", "field/contests/atcoder/abc261", "field/contests/atcoder/abc253", "field/contests/atcoder/abc258", "field/contests/atcoder/abc265", "field/contests/atcoder/abc279", "field/contests/atcoder/abc276", "field/contests/atcoder/abc275", "field/contests/atcoder/tessoku-book", "field/contests/atcoder/abc283", "field/contests/atcoder/abc100", "field/contests/atcoder/abc087", "field/contests/atcoder/agc019", "field/contests/atcoder/abc144", "field/contests/atcoder/agc041", "field/contests/atcoder/abc151", "field/contests/atcoder/abc115", "field/contests/atcoder/agc021", "field/contests/atcoder/abc281", "field/contests/atcoder/abc272", "field/contests/atcoder/abc268", "field/contests/atcoder/abc267", "field/contests/atcoder/abc236", "field/contests/atcoder/abc261", "field/contests/atcoder/abc253", "field/contests/atcoder/abc258", "field/contests/atcoder/abc265", "field/contests/atcoder/abc279", "field/contests/atcoder/abc276", "field/contests/atcoder/abc275", "field/contests/atcoder/abc271","field/contests/atcoder/tessoku-book", "field/contests/atcoder/abc284", "field/contests/atcoder/abc217", "field/contests/atcoder/rco-contest-2019-qual", "field/contests/atcoder/abc049", "field/contests/atcoder/abc285", "field/contests/atcoder/abc160", "field/contests/atcoder/arc154", "field/contests/atcoder/abc286", "field/contests/atcoder/abc287", "field/contests/atcoder/abc288", "field/contests/atcoder/abc289", "field/contests/atcoder/abc290", "field/contests/atcoder/ahc018", "field/contests/atcoder/ahc018/tools", "field/contests/atcoder/abc293", "field/contests/atcoder/abc294", "field/contests/atcoder/abc295", "field/contests/atcoder/arc159", "field/contests/atcoder/abc298", "field/contests/atcoder/abc299", "field/contests/atcoder/abc300", "field/contests/atcoder/abc297", "field/contests/atcoder/abc050", "field/contests/atcoder/abc110", "field/contests/atcoder/abc038", "field/contests/atcoder/abc296", "field/contests/atcoder/agc023", "field/contests/atcoder/abc292", "field/contests/atcoder/abc301"]
exclude = []

[dependencies]
num = "=0.2.1"
num-bigint = "=0.2.6"
num-complex = "=0.2.4"
num-integer = "=0.1.42"
num-iter = "=0.1.40"
num-rational = "=0.2.4"
num-traits = "=0.2.11"
num-derive = "=0.3.0"
ndarray = "=0.13.0"
nalgebra = "=0.20.0"
alga = "=0.9.3"
libm = "=0.2.1"
rand = { version = "=0.7.3", features = ["small_rng"] }
getrandom = "=0.1.14"
rand_chacha = "=0.2.2"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_pcg = "=0.2.1"
rand_distr = "=0.2.2"
petgraph = "=0.5.0"
indexmap = "=1.3.2"
regex = "=1.3.6"
lazy_static = "=1.4.0"
ordered-float = "=1.0.2"
ascii = "=1.0.0"
permutohedron = "=0.2.4"
superslice = "=1.0.0"
itertools = "=0.9.0"
itertools-num = "=0.1.3"
maplit = "=1.0.2"
either = "=1.5.3"
im-rc = "=14.3.0"
fixedbitset = "=0.2.0"
bitset-fixed = "=0.1.0"
proconio = { version = "=0.3.6", features = ["derive"] }
text_io = "=0.1.8"
whiteread = "=0.5.0"
rustc-hash = "=1.1.0"
smallvec = "=1.2.0"
