#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 1000)  # TODO: edit here
    A = [None for _ in range(N - 1)]
    M = random.randint(1, 1000)  # TODO: edit here
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    T = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(N - 1):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(M):
        X[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        Y[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, M, T)
    print(*[A[i] for i in range(N - 1)])
    for i in range(M):
        print(X[i], Y[i])

if __name__ == "__main__":
    main()
