#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

const std::string YES = "Yes";
const std::string NO = "No";
bool solve(int N, int M, int64_t T, const std::vector<int64_t> &A, const std::vector<int64_t> &X, const std::vector<int64_t> &Y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    int64_t T;
    std::cin >> N;
    std::vector<int64_t> A(N - 1);
    std::cin >> M;
    std::vector<int64_t> X(M), Y(M);
    std::cin >> T;
    REP (i, N - 1) {
        std::cin >> A[i];
    }
    REP (i, M) {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, M, T, A, X, Y);
    std::cout << (ans ? YES : NO) << '\n';
    return 0;
}
