#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(N: int, M: int, T: int, A: List[int], X: List[int], Y: List[int]) -> str:
def solve(N, M, T, A, X, Y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    M = int(next(tokens))
    T = int(next(tokens))
    A = [None for _ in range(N - 1)]
    X = [None for _ in range(M)]
    Y = [None for _ in range(M)]
    for i in range(N - 1):
        A[i] = int(next(tokens))
    for i in range(M):
        X[i] = int(next(tokens))
        Y[i] = int(next(tokens))
    assert next(tokens, None) is None
    b = solve(N, M, T, A, X, Y)
    print(b)

if __name__ == '__main__':
    main()
