[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = [ "cdylib", "rlib",]

[profile.dev]
overflow-checks = false

[profile.test]
overflow-checks = false

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.81"

[target.'cfg(target_arch = "wasm32")'.dependencies]
version = "0.2.7"
features = [ "js",]

[dependencies]
