#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(1, 10)  # TODO: edit here
    A = [[None for _ in range(2 * N + 4)] for _ in range(2 * N + 4)]
    for j in range(N + 4):
        for i in range(N):
            A[i + j][i + j] = random.randint(1, 10)  # TODO: edit here
    print(N)
    for j in range(N + 4):
        print(*[A[i + j][i + j] for i in range(N)])

if __name__ == "__main__":
    main()
