#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, M: int) -> List[str]:
def solve(N, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    ans = solve(N, M)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
