#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(A: int, B: int, C: int, D: int, E: int) -> str:
def solve(A, B, C, D, E):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    A, B, C, D, E = map(int, input().split())
    a = solve(A, B, C, D, E)
    print(a)

if __name__ == '__main__':
    main()
