WITH
  AVG AS (
    SELECT
      GOODS_CODE,
      ROUND(AVG(STD_COST_PRICE), 1) AS AVG_PRICE,
      STD_COST_PRICE
    FROM
      SKU
    GROUP BY
      GOODS_CODE
  )
UPDATE SKU
SET
  STD_COST_PRICE = (
    SELECT
      GOODS.STD_COST_PRICE
    FROM
      GOODS
    WHERE
      SKU.GOODS_CODE = GOODS.GOODS_CODE
  ),
  UPDATE_USER_NAME = 'MODIFY',
  USER_UPDATE_DATETIME = '2024-08-31 00:00:00'
FROM
  AVG
WHERE
  AVG.GOODS_CODE = SKU.GOODS_CODE
  AND AVG.AVG_PRICE > SKU.STD_COST_PRICE;

SELECT
  *
FROM
  SKU
