#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, h: int, w: int) -> int:
def solve(H, W, h, w):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W = map(int, input().split())
    h, w = map(int, input().split())
    a = solve(H, W, h, w)
    print(a)

if __name__ == '__main__':
    main()
