#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int) -> int:
def solve(N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    a = solve(N)
    print(a)

if __name__ == '__main__':
    main()
