#!/usr/bin/env python3
# from typing import *

MOD = 998244353

# def solve(N: int, U: List[int], V: List[int]) -> int:
def solve(N, U, V):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    U = [None for _ in range(N - 1)]
    V = [None for _ in range(N - 1)]
    for i in range(N - 1):
        U[i], V[i] = map(int, input().split())
    a = solve(N, U, V)
    print(a)

if __name__ == '__main__':
    main()
