#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;

constexpr int64_t MOD = 998244353;
int64_t solve(auto N, auto M, auto A, auto B, auto C, auto D, auto E, auto F, const std::vector<auto> &X, const std::vector<auto> &Y) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    auto N, M, A, B, C, D, E, F;
    std::cin >> N >> M;
    std::vector<auto> X(M), Y(M);
    std::cin >> A >> B >> C >> D >> E >> F;
    REP (i, M) {
        std::cin >> X[i] >> Y[i];
    }
    auto ans = solve(N, M, A, B, C, D, E, F, X, Y);
    std::cout << ans << '\n';
    return 0;
}
