#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H = random.randint(1, 10)  # TODO: edit here
    W = random.randint(1, 10)  # TODO: edit here
    C = [[None for _ in range(W)] for _ in range(H)]
    f = [".","#"]
    for j in range(H):
        for i in range(W):
            C[j][i] = f[random.randint(0,1)]
    C[0][0] = "."
    print(H, W)
    for j in range(H):
        print("".join(C[j]))

if __name__ == "__main__":
    main()
