#!/usr/bin/env python3
# from typing import *



# def solve(n: int, a: List[int]) -> List[str]:
def solve(n, a):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    n = int(input())
    a = [None for _ in range(n)]
    for i in range(n):
        a[i] = int(input())
    ans = solve(n, a)
    for i in range(n):
        print(ans[i])

if __name__ == '__main__':
    main()
