#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int N, int Q, int64_t X, const std::vector<int64_t> &W, const std::vector<int64_t> &K) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, Q;
    int64_t X;
    std::cin >> N;
    std::vector<int64_t> W(N);
    std::cin >> Q;
    std::vector<int64_t> K(Q);
    std::cin >> X;
    REP (i, N) {
        std::cin >> W[i];
    }
    REP (i, Q) {
        std::cin >> K[i];
    }
    auto ans = solve(N, Q, X, W, K);
    REP (i, Q) {
        std::cout << a[i] << '\n';
    }
    return 0;
}
