#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    a = random.randint(1, 10)  # TODO: edit here
    c = [None for _ in range(a)]
    d = [[None for _ in range(a)] for _ in range(a)]
    b = random.randint(1, 10)  # TODO: edit here
    for i in range(a):
        c[i] = random.randint(1, 10)  # TODO: edit here
        for j in range(i):
            d[i][j] = random.randint(1, 10)  # TODO: edit here
    e = random.randint(1, 10)  # TODO: edit here
    print(a, end=' ')
    print(b, end=' ')
    for i in range(a):
        print(c[i])
        for j in range(i):
            print(d[i][j], end=' ')
    print(e)

if __name__ == "__main__":
    main()
