#!/usr/bin/env python3
# from typing import *



# def solve(H: int, W: int, a: int, b: int) -> Tuple[List[str], List[str]]:
def solve(H, W, a, b):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    H, W, a, b = map(int, input().split())
    h, w = solve(H, W, a, b)
    print(h[0], w[0])

if __name__ == '__main__':
    main()
