#!/usr/bin/env python3
# from typing import *



# def solve(N: int) -> Tuple[int, List[int]]:
def solve(N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = int(input())
    K, t = solve(N)
    print(K)
    for i in range(K):
        print(t[i])

if __name__ == '__main__':
    main()
