#!/usr/bin/env python3
# from typing import *



# def solve(N: int, P: List[int]) -> int:
def solve(N, P):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    P = [None for _ in range(N - 1)]
    for i in range(N - 1):
        P[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, P)
    print(a)

if __name__ == '__main__':
    main()
