#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


auto solve(int64_t N, int64_t M) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int64_t N, M;
    std::cin >> N >> M;
    auto ans = solve(N, M);
    REP (i, N) {
        std::cout << a[i] << ' ';
        REP (j, M) {
            std::cout << c[i][j] << ' ';
        }
        std::cout << '\n';
        REP (j, i) {
            std::cout << f[i][j] << ' ';
            REP (k, i) {
                std::cout << h[i][j][k] << ' ';
            }
            std::cout << '\n';
        }
    }
    return 0;
}
