#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int) -> Tuple[List[str], List[List[str]], List[List[str]], List[List[List[str]]]]:
def solve(N, M):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M = map(int, input().split())
    a, c, f, h = solve(N, M)
    for i in range(N):
        print(a[i], *[c[i][j] for j in range(M)])
        for j in range(i):
            print(f[i][j], *[h[i][j][k] for k in range(i)])

if __name__ == '__main__':
    main()
