#!/usr/bin/env python3
# from typing import *



# def solve(X: int, Y: int, N: int) -> int:
def solve(X, Y, N):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    X, Y, N = map(int, input().split())
    a = solve(X, Y, N)
    print(a)

if __name__ == '__main__':
    main()
