#!/usr/bin/env python3
# from typing import *



# def solve(N: int, M: int, K: int, RX: List[int], RY: List[int], BX: List[int], BY: List[int]) -> int:
def solve(N, M, K, RX, RY, BX, BY):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N, M, K = map(int, input().split())
    RX = [None for _ in range(N)]
    RY = [None for _ in range(N)]
    BX = [None for _ in range(M)]
    BY = [None for _ in range(M)]
    for i in range(N):
        RX[i], RY[i] = map(int, input().split())
    for i in range(M):
        BX[i], BY[i] = map(int, input().split())
    a = solve(N, M, K, RX, RY, BX, BY)
    print(a)

if __name__ == '__main__':
    main()
