#include <iostream>
#include <string>
#include <vector>
#define REP(i, n) for (int i = 0; (i) < (int)(n); ++ (i))
#define REP3(i, m, n) for (int i = (m); (i) < (int)(n); ++ (i))
#define REP_R(i, n) for (int i = (int)(n) - 1; (i) >= 0; -- (i))
#define REP3R(i, m, n) for (int i = (int)(n) - 1; (i) >= (int)(m); -- (i))
#define ALL(x) ::std::begin(x), ::std::end(x)
using namespace std;


int64_t solve(int N, int M, int64_t K, const std::vector<int64_t> &RX, const std::vector<int64_t> &RY, const std::vector<int64_t> &BX, const std::vector<int64_t> &BY) {
    // TODO: edit here
}

// generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
int main() {
    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);
    int N, M;
    int64_t K;
    std::cin >> N;
    std::vector<int64_t> RX(N), RY(N);
    std::cin >> M;
    std::vector<int64_t> BX(M), BY(M);
    std::cin >> K;
    REP (i, N) {
        std::cin >> RX[i] >> RY[i];
    }
    REP (i, M) {
        std::cin >> BX[i] >> BY[i];
    }
    auto ans = solve(N, M, K, RX, RY, BX, BY);
    std::cout << ans << '\n';
    return 0;
}
