#!/usr/bin/env python3
# from typing import *

MOD = 1000000007

# def solve(N: int, A: List[int]) -> int:
def solve(N, A):
    mod = 10**9+7

    dp = [[0]*2 for _ in range(N)]
    dp[0][0] = A[0]

    ans = 0
    for i in range(N-1):
        # dp[i][1]: A[i]の前が"+"、dp[i][0]: A[i]の前が"-"
        if i == 0:
            dp[i+1][1] = dp[i][0] + A[i+1]
            dp[i+1][0] = dp[i][0] - A[i+1]
        else:
            dp[i+1][1] = dp[i][1] + A[i+1] + dp[i][0] + A[i+1]
            dp[i+1][0] = dp[i][1] - A[i+1]

    # print(dp)
    return sum(dp[N-1])%mod

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = int(next(tokens))
    assert next(tokens, None) is None
    a = solve(N, A)
    print(a)

if __name__ == '__main__':
    main()
