dependencies = [ "once_cell = \"=1.18.0\"", "static_assertions = \"=1.1.0\"", "varisat = \"=0.2.2\"", "memoise = \"=0.3.2\"", "argio = \"=0.2.0\"", "ac-library-rs = \"=0.1.1\"",]
[[bin]]
name = "chokudai_s001-a"
path = "src/bin/a.rs"

[[bin]]
name = "chokudai_s001-b"
path = "src/bin/b.rs"

[[bin]]
name = "chokudai_s001-c"
path = "src/bin/c.rs"

[[bin]]
name = "chokudai_s001-d"
path = "src/bin/d.rs"

[[bin]]
name = "chokudai_s001-e"
path = "src/bin/e.rs"

[[bin]]
name = "chokudai_s001-f"
path = "src/bin/f.rs"

[[bin]]
name = "chokudai_s001-g"
path = "src/bin/g.rs"

[[bin]]
name = "chokudai_s001-h"
path = "src/bin/h.rs"

[[bin]]
name = "chokudai_s001-i"
path = "src/bin/i.rs"

[[bin]]
name = "chokudai_s001-j"
path = "src/bin/j.rs"

[[bin]]
name = "chokudai_s001-k"
path = "src/bin/k.rs"

[[bin]]
name = "chokudai_s001-l"
path = "src/bin/l.rs"

[package]
name = "chokudai_s001"
version = "0.1.0"
edition = "2018"

[dev-dependencies]

[package.metadata.cargo-compete.bin.chokudai_s001-a]
alias = "a"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_a"

[package.metadata.cargo-compete.bin.chokudai_s001-b]
alias = "b"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_b"

[package.metadata.cargo-compete.bin.chokudai_s001-c]
alias = "c"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_c"

[package.metadata.cargo-compete.bin.chokudai_s001-d]
alias = "d"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_d"

[package.metadata.cargo-compete.bin.chokudai_s001-e]
alias = "e"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_e"

[package.metadata.cargo-compete.bin.chokudai_s001-f]
alias = "f"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_f"

[package.metadata.cargo-compete.bin.chokudai_s001-g]
alias = "g"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_g"

[package.metadata.cargo-compete.bin.chokudai_s001-h]
alias = "h"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_h"

[package.metadata.cargo-compete.bin.chokudai_s001-i]
alias = "i"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_i"

[package.metadata.cargo-compete.bin.chokudai_s001-j]
alias = "j"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_j"

[package.metadata.cargo-compete.bin.chokudai_s001-k]
alias = "k"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_k"

[package.metadata.cargo-compete.bin.chokudai_s001-l]
alias = "l"
problem = "https://atcoder.jp/contests/chokudai_s001/tasks/chokudai_S001_l"
